# Generated by Django 5.0.4 on 2024-07-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_pharmaceutical_form'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='AmountReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reminder_quantity', models.IntegerField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medications.medication')),
            ],
        ),
    ]
