# Generated by Django 5.0.4 on 2024-07-07 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_pharmaceutical_form'),
        ('reminders', '0003_alter_amountreminder_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountreminder',
            name='medication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medications.medication'),
        ),
    ]
