# Generated by Django 5.0.4 on 2024-07-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_pharmaceutical_form'),
        ('reminders', '0004_alter_amountreminder_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountreminder',
            name='low_stock',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='amountreminder',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='amountreminder',
            name='medication',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medications.medication'),
        ),
        migrations.AlterField(
            model_name='amountreminder',
            name='reminder_quantity',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency_per_day',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='medication',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medications.medication'),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='remind_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('daily reminder', 'Daily Reminder'), ('unique reminder', 'Unique Reminder')], max_length=20),
        ),
    ]
