# Generated by Django 5.0.4 on 2024-08-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_remove_medicationreminder_medication_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='day',
            field=models.DateField(blank=True),
        ),
    ]
