# Generated by Django 5.0.4 on 2024-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Medication name')),
                ('pharmaceutical_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('solution', 'Solution'), ('liquid', 'Liquid'), ('injectable', 'Injectable')], max_length=20, verbose_name='Pharmaceutical form')),
                ('patient_id', models.IntegerField(blank=True, null=True, verbose_name='patient id')),
            ],
        ),
    ]
